version: '3.8'
name: "godj"
services:
  mongo:
    #user: ${CURRENT_UID}
    image: mongo:latest
    container_name: godj-mongo
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=BuildMeUp
#      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27018:27017"
    volumes:
     - ${GODJ_DATA:-.}/.volumes/mongo:/data/db
     #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
     #./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
